### ISSUE TITLE
Build chat connection to API

### ISSUE THREAD

**Issue by njons** [fac-14/Vent-Bot#11]
**One event to start a chain of responses:**
- [x] Event added to the _send indicator_

**1. User can type a response, press send and see their message added to the screen**
- [x] User input extracted from the DOM (/send-data)
- [x] User input sent as buffer via a POST request to the controller 
- [x] Ensure that the data is collected in the controller

**2. User input is added to chat** 
- [x] Move the user input from the text bar to the chat window at _send event_   

**3. User can see an indicator that the bot is responding**
- [x] Add 'waiting/thinking' indicator at _send event_

User can see a way to exit the conversation
- [x] Add indicator to leave chat and navigate back to home page
